### ISSUE TITLE
SCSN2021 data set

### ISSUE THREAD

**Issue by jyystar789** [lovelytt0/EdgePhase#1]
Hello, Dr. Feng,

I would like to know where do you get the SCSN2021 data set from SCSN?

**Comment by lovelytt0** [comment]
Hi,

Please reference the website
https://scedc.caltech.edu/data/cloud.html#waveforms. You can find the
earthquake catalog and station information in AWS buckets.

Tian

**Comment by jyystar789** [comment]
Ok, thank you very much.
